version: '3'

services:
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ./web-app:/var/www

  nginx:
    build:
      context: ./nginx
    volumes:
      - ./web-app:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "8080:80"
      - "443:443"

  #База знаний (онтология)
  family-ontology:
    build: ./ontology
    image: family/ontology:latest
    container_name: ontology
    ports:
      - 8081:80
    networks:
      - family-network

networks:
  family-network: {}
